package com.hnzy.hot.util;

public class DUtil {
	
	private static String bsbgzfk_1="宝石花1200.机组1.1#补水泵故障反馈";private static String bsbgzfk_2="宝石花1200.机组1.2#补水泵故障反馈";   	
   	private static String bsbyxfk_1="宝石花1200.机组1.1#补水泵运行反馈";private static String bsbyxfk_2="宝石花1200.机组1.2#补水泵运行反馈";
   	private static String bsbyxsj_1="宝石花1200.机组1.1#补水泵运行时间";private static String bsbyxsj_2="宝石花1200.机组1.2#补水泵运行时间";
   	private static String bsbyxsjql_1="宝石花1200.机组1.1#补水泵运行时间清零";private static String bsbyxsjql_2="宝石花1200.机组1.2#补水泵运行时间清零";
	private static String bsbzdyxkg_1="宝石花1200.机组1.1#补水泵自动允许开关";private static String bsbzdyxkg_2="宝石花1200.机组1.2#补水泵自动允许开关";
	
	private static String xhbgzfk_1="宝石花1200.机组1.1#循环泵故障反馈";private static String xhbgzfk_2="宝石花1200.机组1.2#循环泵故障反馈";   	
   	private static String xhbyxfk_1="宝石花1200.机组1.1#循环泵运行反馈";private static String xhbyxfk_2="宝石花1200.机组1.2#循环泵运行反馈";
   	private static String xhbyxsj_1="宝石花1200.机组1.1#循环泵运行时间";private static String xhbyxsj_2="宝石花1200.机组1.2#循环泵运行时间";
   	private static String xhbyxsjql_1="宝石花1200.机组1.1#循环泵运行时间清零";private static String xhbyxsjql_2="宝石花1200.机组1.2#循环泵运行时间清零";
	private static String xhbzdyxkg_1="宝石花1200.机组1.1#循环泵自动允许开关";private static String xhbzdyxkg_2="宝石花1200.机组1.2#循环泵自动允许开关";
	private static String btlsd="宝石花1200.机组1.波特率设定";
	private static String bsbPIDblsd="宝石花1200.机组1.补水泵PID比例设定";
	private static String bsbPIDjfsd="宝石花1200.机组1.补水泵PID积分设定";
	private static String bsbPIDwjfsd="宝石花1200.机组1.补水泵PID微分设定";
	private static String bsbdbsjsd="宝石花1200.机组1.补水泵倒泵时间设定";
	private static String bsbplfk="宝石花1200.机组1.补水泵频率反馈";
	private static String bsbszdqh="宝石花1200.机组1.补水泵手自动切换";
	private static String bsbyxdb="宝石花1200.机组1.补水泵允许倒泵";
	private static String bsbpqgz="宝石花1200.机组1.补水变频器故障";
	private static String bshxpcsd="宝石花1200.机组1.补水唤醒偏差设定";
	private static String bsplsd="宝石花1200.机组1.补水频率设定";
	private static String bssmplsd="宝石花1200.机组1.补水睡眠频率设定";
	private static String bsylsd="宝石花1200.机组1.补水压力设定";
	private static String czbtlsd="宝石花1200.机组1.从站波特率设定";
	private static String czjojysd="宝石花1200.机组1.从站奇偶校验设定";
	private static String ddfPIDblsd="宝石花1200.机组1.电动阀PID比例设定";
	private static String ddfPIDjfsd="宝石花1200.机组1.电动阀PID积分设定";
	private static String ddfPIDwfsd="宝石花1200.机组1.电动阀PID微分设定";
	private static String ddfszdqh="宝石花1200.机组1.电动阀手自动切换";
	private static String ddtjffwfk="宝石花1200.机组1.电动调节阀阀位反馈";
	private static String ecghsyc="宝石花1200.机组1.二次供回水压差";
	private static String ecgscwbj="宝石花1200.机组1.二次供水超温报警";
	private static String ecgscybj="宝石花1200.机组1.二次供水超压报警";
	private static String ecgsdwbj="宝石花1200.机组1.二次供水低温报警";
	private static String ecgswd="宝石花1200.机组1.二次供水温度";
	private static String ecgswdgdsdz="宝石花1200.机组1.二次供水温度过低设定值";
	private static String ecgswdggsdz="宝石花1200.机组1.二次供水温度过高设定值";
	private static String ecgsyl="宝石花1200.机组1.二次供水压力";
	private static String ecgsylgxbhsd="宝石花1200.机组1.二次供水压力高限保护设定";
	private static String ecgsylgxtxhb="宝石花1200.机组1.二次供水压力高限停循环泵";
	private static String echsyldxbhsd="宝石花1200.机组1.二次回水压力低限保护设定";
	private static String echsyldxtxhb="宝石花1200.机组1.二次回水压力低限停循环泵";
	private static String ecgsylggsdz="宝石花1200.机组1.二次供水压力过高设定值";
	private static String echsylgdsdz="宝石花1200.机组1.二次回水压力过低设定值";
	private static String echssybj="宝石花1200.机组1.二次回水失压报警";
	private static String echswd="宝石花1200.机组1.二次回水温度";
	private static String echsyl="宝石花1200.机组1.二次回水压力";
	private static String ecljll="宝石花1200.机组1.二次累计流量";
	private static String eclljjlxs="宝石花1200.机组1.二次流量计累积系数";
	private static String eclljzdzsd="宝石花1200.机组1.二次流量计站地址设定";
	private static String ecssll="宝石花1200.机组1.二次瞬时流量";
	private static String ecylbsqdxlcsd="宝石花1200.机组1.二次压力变送器低限量程设定";
	private static String ecylbsqgxlcsd="宝石花1200.机组1.二次压力变送器高限量程设定";
	private static String gzbj="宝石花1200.机组1.故障报警";
	private static String jojysd="宝石花1200.机组1.奇偶校验设定";
	private static String sdgswdsd1="宝石花1200.机组1.时段供水温度设定1";private static String sdgswdsd5="宝石花1200.机组1.时段供水温度设定5";
	private static String sdgswdsd2="宝石花1200.机组1.时段供水温度设定2";private static String sdgswdsd6="宝石花1200.机组1.时段供水温度设定6";
	private static String sdgswdsd3="宝石花1200.机组1.时段供水温度设定3";private static String sdgswdsd7="宝石花1200.机组1.时段供水温度设定7";
	private static String sdgswdsd4="宝石花1200.机组1.时段供水温度设定4";
	private static String sdsd1="宝石花1200.机组1.时段设定1";private static String sdsd4="宝石花1200.机组1.时段设定4";
	private static String sdsd2="宝石花1200.机组1.时段设定2";private static String sdsd5="宝石花1200.机组1.时段设定5";
	private static String sdsd3="宝石花1200.机组1.时段设定3";private static String sdsd6="宝石花1200.机组1.时段设定6";
	private static String sdkdsd="宝石花1200.机组1.手动开度设定";
	private static String wdbsqdxlcsd="宝石花1200.机组1.温度变送器低限量程设定";
	private static String wdbsqgxlcsd="宝石花1200.机组1.温度变送器高限量程设定";
	private static String xhbPIDblsd="宝石花1200.机组1.循环泵PID比例设定";
	private static String xhbPIDjfsd="宝石花1200.机组1.循环泵PID积分设定";
	private static String xhbPIDwfsd="宝石花1200.机组1.循环泵PID微分设定";
	private static String xhbdbsjsd="宝石花1200.机组1.循环泵倒泵时间设定";
	private static String xhbplfk="宝石花1200.机组1.循环泵频率反馈";
	private static String xhbszdqh="宝石花1200.机组1.循环泵手自动切换";
	private static String xhbyxdb="宝石花1200.机组1.循环泵允许倒泵";
	private static String xhbbpqgz="宝石花1200.机组1.循环变频器故障";
	private static String xhplsd="宝石花1200.机组1.循环频率设定";
	private static String xhycsd="宝石花1200.机组1.循环压差设定";
	private static String ycgswd="宝石花1200.机组1.一次供水温度";
	private static String ycgsyl="宝石花1200.机组1.一次供水压力";
	private static String ychscwbj="宝石花1200.机组1.一次回水超温报警";
	private static String ychswd="宝石花1200.机组1.一次回水温度";
	private static String ychswdggsdz="宝石花1200.机组1.一次回水温度过高设定值";
	private static String ychsyl="宝石花1200.机组1.一次回水压力";
	private static String ycljll="宝石花1200.机组1.一次累计流量";
	private static String yclljljxs="宝石花1200.机组1.一次流量计累积系数";
	private static String yclljzdzsd="宝石花1200.机组1.一次流量计站地址设定";
	private static String ycssll="宝石花1200.机组1.一次瞬时流量";
	private static String ycylbsqdxlcsd="宝石花1200.机组1.一次压力变送器低限量程设定";
	private static String ycylbsqgxlcsd="宝石花1200.机组1.一次压力变送器高限量程设定";
	private static String yyoreyxzBSB="宝石花1200.机组1.一用or二用选择BSB";
	private static String yyoreyxzXHB="宝石花1200.机组1.一用or二用选择XHB";
	private static String zdwdsd="宝石花1200.机组1.自动温度设定";
}
